# Generated by Django 5.2.6 on 2025-09-21 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_order_alter_student_photo_pos_order_order_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='price',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
