# Generated by Django 5.2.6 on 2025-09-21 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_teacher_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='clothes',
            new_name='teachers',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
