# Generated by Django 5.2.6 on 2025-09-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_clothes_order_teachers_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos_order',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
