# Generated by Django 5.2.6 on 2025-09-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_rename_teachers_pos_order_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
    ]
